# Default Gemfile generated by executing `bundle init`.
# Add required packages to the end of the file.

# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "jekyll"
# To use a remote theme locally, the following package is needed:
gem "jekyll-remote-theme"
# But this doesn't account for dependencies of the remote theme!
# Install the theme gem to make sure we locally have all the packages needed.
gem "minimal-mistakes-jekyll"
